const fs = require('fs');
const q = require('/home/claude/node_modules/quran-json/dist/quran.json');

// Surah names from quran-json
const surahNames = {};
q.forEach(s => { surahNames[s.id] = {sa: s.name, se: s.transliteration}; });

// Corpus from Tanzil Simple (Clean) — already diacritic-free, no stripping needed
const tanzilPath = fs.existsSync('/home/claude/quran-simple-clean.txt')
  ? '/home/claude/quran-simple-clean.txt'
  : '/mnt/user-data/uploads/quran-simple-clean__2_.txt';

const lines = fs.readFileSync(tanzilPath, 'utf8')
  .split('\n').filter(l => l.trim() && !l.startsWith('#'));

const data = lines.map(l => {
  const parts = l.split('|');
  const sn = +parts[0], an = +parts[1], text = parts.slice(2).join('|').trim();
  const s = surahNames[sn];
  return [sn, s.sa, s.se, an, text];
});
console.log('Total verses:', data.length);
console.log('7:2:', data.find(r=>r[0]===7&&r[3]===2)[4]);

const quranJS = 'const QURAN=' + JSON.stringify(data) + ';';

// Build autocomplete prefix map from corpus (frequency-ranked)
const wordFreq = {};
data.forEach(r => r[4].split(' ').forEach(w => { if(w.length>1) wordFreq[w]=(wordFreq[w]||0)+1; }));
const wordsByFreq = Object.keys(wordFreq).sort((a,b) => wordFreq[b]-wordFreq[a]);
const prefixMap = {};
wordsByFreq.forEach(w => {
  for (let len=2; len<=Math.min(w.length,4); len++) {
    const p = w.slice(0,len);
    if(!prefixMap[p]) prefixMap[p]=[];
    if(prefixMap[p].length<5) prefixMap[p].push(w);
  }
});
const autocompleteJS = 'const AC=' + JSON.stringify(prefixMap) + ';';
console.log('Autocomplete prefixes:', Object.keys(prefixMap).length);


// Default shared equivs — shipped in equivs.json alongside the HTML
const defaultEquivs = [
  ['الرحمن', 'الرحمان'],
  ['ملك', 'مالك'],
];
fs.writeFileSync('/home/claude/equivs.json', JSON.stringify(defaultEquivs, null, 2));
console.log('equivs.json written with', defaultEquivs.length, 'default pairs');

const css = ''
+ '*{box-sizing:border-box;margin:0;padding:0}\n'
+ 'body{font-family:\'Amiri\',\'Traditional Arabic\',serif;background:#1a1a1a;color:#e8e0d0;display:flex;flex-direction:column;align-items:center;padding:12px 16px}\n'
+ '.container{width:100%;max-width:720px;display:flex;flex-direction:column;gap:7px}\n'
// Selector
+ '.selector-bar{display:flex;align-items:center;gap:6px;direction:ltr;flex-wrap:wrap}\n'
+ '.selector-bar select,.selector-bar input[type=number]{font-family:sans-serif;font-size:13px;padding:5px 8px;border-radius:7px;border:1px solid #363636;background:#252525;color:#ccc;outline:none}\n'
+ '.selector-bar select{flex:1;min-width:160px}\n'
+ '.selector-bar select:focus,.selector-bar input[type=number]:focus{border-color:#2a5438}\n'
+ '.selector-bar input[type=number]{width:62px;text-align:center}\n'
+ '.nav-btn{font-family:sans-serif;font-size:16px;padding:4px 9px;border-radius:7px;border:1px solid #363636;background:#252525;color:#888;cursor:pointer}\n'
+ '.nav-btn:hover{background:#2f2f2f;color:#ccc}\n'
+ '.ayah-label{font-family:sans-serif;font-size:11px;color:#555;white-space:nowrap}\n'
// Panels
+ '.panel{border-radius:10px;padding:10px 14px;position:relative}\n'
+ '.panel-input{background:#252525;border:1px solid #363636}\n'
+ '.panel-ref{background:#1e1e1e;border:1px solid #2d2d2d}\n'
+ '.panel-label{font-family:sans-serif;font-size:10px;color:#555;position:absolute;top:8px;right:12px}\n'
+ 'textarea{width:100%;background:transparent;border:none;outline:none;resize:none;font-size:40px;line-height:1.75;font-family:\'Amiri\',\'Traditional Arabic\',serif;color:#ddd8cc;direction:rtl;text-align:right;margin-top:20px;height:68px;caret-color:#8ab4f8}\n'
+ '.ref-text{font-size:40px;line-height:1.75;direction:rtl;text-align:right;margin-top:20px;min-height:40px;word-spacing:3px}\n'
+ '.ref-meta{font-family:sans-serif;font-size:10px;color:#454545;position:absolute;bottom:7px;left:12px;direction:ltr}\n'
// Toolbar
+ '.toolbar{display:flex;align-items:center;gap:8px;direction:ltr;flex-wrap:wrap}\n'
+ 'button.action{font-family:sans-serif;font-size:12px;font-weight:500;padding:5px 14px;border-radius:7px;border:1px solid #363636;background:#252525;color:#bbb;cursor:pointer;transition:background .15s}\n'
+ 'button.action:hover{background:#2f2f2f}\n'
+ 'button.primary{background:#162d20;border-color:#2a5438;color:#5ec48a}\n'
+ 'button.primary:hover{background:#1b3828}\n'
+ '.meta{font-family:sans-serif;font-size:11px;color:#555;direction:ltr}\n'
// Score bar
+ '.score-bar{height:2px;border-radius:2px;background:#2a2a2a;margin-top:6px;overflow:hidden}\n'
+ '.score-fill{height:100%;border-radius:2px;transition:width .4s,background .4s;width:0%}\n'
// Word diff
+ '.w-match{color:#5ec48a}\n'
+ '.w-wrong{color:#e07070;text-decoration:underline wavy #e07070 1.5px;text-underline-offset:3px}\n'
+ '.w-missing{color:#2e2e2e}\n'
+ '@keyframes flashGreen{0%{border-color:#2a5438}50%{border-color:#5ec48a}100%{border-color:#2d2d2d}}\n'
+ '.success-flash{animation:flashGreen .6s ease}\n'
// History panel
+ '.history-panel{background:#181818;border:1px solid #272727;border-radius:10px;overflow:hidden}\n'
+ '.history-header{display:flex;align-items:center;justify-content:space-between;padding:7px 12px;direction:ltr;cursor:pointer;user-select:none}\n'
+ '.history-header span{font-family:sans-serif;font-size:11px;color:#555}\n'
+ '.history-scroll{max-height:280px;overflow-y:auto;display:none}\n'
+ '.history-scroll.open{display:block}\n'
+ '.history-item{padding:10px 14px;border-top:1px solid #222;direction:rtl}\n'
+ '.history-item:first-child{border-top:none}\n'
+ '.h-meta{font-family:sans-serif;font-size:10px;color:#555;direction:ltr;margin-bottom:4px;display:flex;justify-content:space-between}\n'
+ '.h-typed{font-size:18px;line-height:1.6;color:#666;margin-bottom:3px;direction:rtl}\n'
+ '.h-ref{font-size:18px;line-height:1.6;direction:rtl}\n'
// Equivalents panel
+ '.equiv-panel{background:#1e1e1e;border:1px solid #2d2d2d;border-radius:10px;overflow:hidden}\n'
+ '.equiv-header{display:flex;align-items:center;justify-content:space-between;padding:7px 12px;direction:ltr;cursor:pointer;user-select:none}\n'
+ '.equiv-header span{font-family:sans-serif;font-size:11px;color:#555}\n'
+ '.equiv-body{display:none;padding:8px 12px 10px}\n'
+ '.equiv-body.open{display:block}\n'
+ '.equiv-add{display:flex;gap:5px;margin-bottom:8px;direction:ltr}\n'
+ '.equiv-add input{flex:1;font-family:\'Amiri\',\'Traditional Arabic\',serif;font-size:17px;padding:4px 8px;border-radius:7px;border:1px solid #363636;background:#252525;color:#ccc;outline:none;direction:rtl;text-align:right}\n'
+ '.equiv-add input:focus{border-color:#2a5438}\n'
+ '.equiv-add .sep{font-family:sans-serif;font-size:16px;color:#555;align-self:center}\n'
+ '.equiv-list{display:flex;flex-wrap:wrap;gap:5px}\n'
+ '.equiv-tag{display:inline-flex;align-items:center;gap:4px;background:#252525;border:1px solid #363636;border-radius:5px;padding:2px 6px 2px 4px;font-family:\'Amiri\',\'Traditional Arabic\',serif;font-size:15px;direction:rtl}\n'
+ '.equiv-tag.shared{border-color:#2a5438;color:#5ec48a;background:#162d20}\n'
+ '.equiv-tag .del{font-family:sans-serif;font-size:11px;color:#555;cursor:pointer;border:none;background:none;padding:0 1px}\n'
+ '.equiv-tag .del:hover{color:#e07070}\n'
// On-screen keyboard
+ '.kbd-panel{background:#1e1e1e;border:1px solid #2d2d2d;border-radius:10px;padding:8px 10px;direction:ltr;display:none}\n'
+ '.kbd-panel.open{display:block}\n'
+ '.kbd-row{display:flex;gap:4px;margin-bottom:4px;justify-content:center}\n'
+ '.kbd-key{font-family:\'Amiri\',\'Traditional Arabic\',serif;font-size:19px;min-width:34px;height:38px;padding:0 4px;border-radius:6px;border:1px solid #363636;background:#252525;color:#ddd8cc;cursor:pointer;display:flex;align-items:center;justify-content:center;transition:background .1s;user-select:none}\n'
+ '.kbd-key:hover{background:#333}\n'
+ '.kbd-key:active{background:#3a3a3a;transform:scale(0.95)}\n'
+ '.kbd-key.wide{min-width:72px;font-family:sans-serif;font-size:12px;color:#888}\n'
+ '.kbd-key.space{flex:1;max-width:240px;font-family:sans-serif;font-size:11px;color:#555}\n'
+ '.kbd-toggle{font-family:sans-serif;font-size:16px;padding:3px 8px;border-radius:7px;border:1px solid #363636;background:#252525;color:#666;cursor:pointer;line-height:1}\n'
+ '.kbd-toggle:hover{background:#2f2f2f;color:#aaa}\n'
+ '.ac-wrap{position:relative}\n'
+ '.ac-drop{position:absolute;top:calc(100% + 2px);right:0;left:0;background:#252525;border:1px solid #2a5438;border-radius:8px;z-index:100;overflow:hidden;display:none;direction:rtl;box-shadow:0 4px 12px rgba(0,0,0,.4)}\n'
+ '.ac-drop.open{display:block}\n'
+ '.ac-item{padding:5px 14px;font-family:\'Amiri\',\'Traditional Arabic\',serif;font-size:26px;color:#ddd8cc;cursor:pointer}\n'
+ '.ac-item:hover,.ac-item.active{background:#1b3828;color:#5ec48a}\n';

const js = ''
+ quranJS + '\n'
+ autocompleteJS + '\n'
+ '\n'
+ 'var SURAH_MAP={},SURAHS=[];\n'
+ 'QURAN.forEach(function(r){var sn=r[0],sa=r[1],se=r[2],an=r[3],text=r[4];if(!SURAH_MAP[sn]){SURAH_MAP[sn]={sa:sa,se:se,ayahs:[]};SURAHS.push({sn:sn,sa:sa,se:se});}SURAH_MAP[sn].ayahs.push({an:an,text:text});});\n'
+ '\n'
+ 'var sel=document.getElementById("surah-sel");\n'
+ 'SURAHS.forEach(function(s){var o=document.createElement("option");o.value=s.sn;o.textContent=s.sn+". "+s.sa+" \u2014 "+s.se;sel.appendChild(o);});\n'
+ '\n'
// Equivalents — SHARED (from equivs.json) + LOCAL (localStorage)
+ 'var SHARED_EQUIVS=[], LOCAL_EQUIVS=[];\n'
+ '\n'
+ 'function loadEquivs(){\n'
+ '  try{LOCAL_EQUIVS=JSON.parse(localStorage.getItem("hifz_equivs")||"[]");}catch(e){LOCAL_EQUIVS=[];}\n'
+ '  fetch("equivs.json").then(function(r){return r.json();}).then(function(d){\n'
+ '    SHARED_EQUIVS=Array.isArray(d)?d:[];\n'
+ '    renderEquivTags();\n'
+ '  }).catch(function(){\n'
+ '    SHARED_EQUIVS=[];\n'
+ '    renderEquivTags();\n'
+ '  });\n'
+ '}\n'
+ '\n'
+ 'function allEquivs(){return SHARED_EQUIVS.concat(LOCAL_EQUIVS);}\n'
+ '\n'
+ 'function saveLocal(){localStorage.setItem("hifz_equivs",JSON.stringify(LOCAL_EQUIVS));}\n'
+ '\n'
+ 'function isMatch(inp,ref){\n'
+ '  var normRef=normInput(ref);\n'
+ '  if(inp===normRef)return true;\n'
+ '  var all=allEquivs();\n'
+ '  for(var i=0;i<all.length;i++){var p=all[i];if((p[0]===inp&&p[1]===normRef)||(p[1]===inp&&p[0]===normRef))return true;}\n'
+ '  return false;\n'
+ '}\n'
+ '\n'
+ 'function normInput(t){\n'
+ '  if(!t)return"";\n'
+ '  return t\n'
+ '    .replace(/[\\u064B-\\u065F\\u0670\\u06D6-\\u06DC\\u06DF-\\u06E8\\u06EA-\\u06ED]/g,"")\n'
+ '    .replace(/\\u0640/g,"")\n'
+ '    .replace(/[\\u0623\\u0625\\u0622\\u0671]/g,"\\u0627")\n'
+ '    .replace(/\\u0649\\u0670/g,"\\u064A")\n'
+ '    .replace(/\\u06CC|\\u0649/g,"\\u064A")\n'
+ '    .replace(/\\u06A9/g,"\\u0643")\n'
+ '    .replace(/[\\u06C1\\u06BE]/g,"\\u0647")\n'
+ '    .replace(/\\u06C3/g,"\\u0629")\n'
+ '    .replace(/\\s+/g," ").trim();\n'
+ '}\n'
+ '\n'
+ 'function addEquiv(){\n'
+ '  var a=normInput(document.getElementById("eq-a").value.trim());\n'
+ '  var b=normInput(document.getElementById("eq-b").value.trim());\n'
+ '  if(!a||!b||a===b)return;\n'
+ '  var all=allEquivs();\n'
+ '  for(var i=0;i<all.length;i++){var p=all[i];if((p[0]===a&&p[1]===b)||(p[1]===a&&p[0]===b))return;}\n'
+ '  LOCAL_EQUIVS.push([a,b]);saveLocal();renderEquivTags();\n'
+ '  document.getElementById("eq-a").value="";\n'
+ '  document.getElementById("eq-b").value="";\n'
+ '  document.getElementById("eq-a").focus();\n'
+ '}\n'
+ '\n'
+ 'function removeLocalEquiv(i){LOCAL_EQUIVS.splice(i,1);saveLocal();renderEquivTags();}\n'
+ '\n'
+ 'function renderEquivTags(){\n'
+ '  var cnt=document.getElementById("equiv-count");\n'
+ '  var total=allEquivs().length;\n'
+ '  if(cnt)cnt.textContent=total?"("+total+")" :"";\n'
+ '  var list=document.getElementById("equiv-list");\n'
+ '  var html="";\n'
// Shared pairs (read-only, shown in green)
+ '  SHARED_EQUIVS.forEach(function(p){\n'
+ '    html+="<span class=\'equiv-tag shared\'>"+p[0]+"<span style=\'font-family:sans-serif;font-size:11px;padding:0 3px\'>=</span>"+p[1]+"</span>";\n'
+ '  });\n'
// Local pairs (deletable)
+ '  LOCAL_EQUIVS.forEach(function(p,i){\n'
+ '    html+="<span class=\'equiv-tag\'>"+p[0]+"<span style=\'font-family:sans-serif;font-size:11px;padding:0 3px\'>=</span>"+p[1]+"<button class=\'del\' onclick=\'removeLocalEquiv("+i+")\'>x</button></span>";\n'
+ '  });\n'
+ '  if(!html)html="<span style=\'font-family:sans-serif;font-size:10px;color:#444\'>None yet</span>";\n'
+ '  list.innerHTML=html;\n'
+ '}\n'
+ '\n'
+ 'function toggleEquiv(){\n'
+ '  var body=document.getElementById("equiv-body");\n'
+ '  var open=body.classList.toggle("open");\n'
+ '  document.getElementById("equiv-tog").textContent=open?"\u25b2":"\u25bc";\n'
+ '}\n'
+ '\n'
// History
+ 'var HISTORY=[];\n'
+ '\n'
+ 'function pushHistory(entry){\n'
+ '  HISTORY.unshift(entry);\n'
+ '  renderHistory();\n'
+ '  var hs=document.getElementById("history-scroll");\n'
+ '  if(!hs.classList.contains("open")){hs.classList.add("open");document.getElementById("history-tog").textContent="\u25b2";}\n'
+ '  var hc=document.getElementById("history-count");\n'
+ '  if(hc)hc.textContent="("+HISTORY.length+")";\n'
+ '}\n'
+ '\n'
+ 'function renderHistory(){\n'
+ '  var el=document.getElementById("history-list");\n'
+ '  if(!HISTORY.length){el.innerHTML="<div style=\'padding:10px 14px;font-family:sans-serif;font-size:11px;color:#444\'>No history yet</div>";return;}\n'
+ '  el.innerHTML=HISTORY.map(function(h){\n'
+ '    var pctColor=h.pct>=95?"#5ec48a":h.pct>=50?"#c8943a":"#e07070";\n'
+ '    var refHtml=h.diff.map(function(d){\n'
+ '      var cls=d.missing?"w-missing":d.match?"w-match":"w-wrong";\n'
+ '      return "<span class=\'"+cls+"\'>" +d.r+" </span>";\n'
+ '    }).join("");\n'
+ '    return "<div class=\'history-item\'>"\n'
+ '      +"<div class=\'h-meta\'><span>"+h.label+"</span><span style=\'color:"+pctColor+"\'>"+h.pct+"%</span></div>"\n'
+ '      +"<div class=\'h-typed\'>"+h.typed+"</div>"\n'
+ '      +"<div class=\'h-ref\'>"+refHtml+"</div>"\n'
+ '      +"</div>";\n'
+ '  }).join("");\n'
+ '}\n'
+ '\n'
+ 'function toggleHistory(){\n'
+ '  var hs=document.getElementById("history-scroll");\n'
+ '  var open=hs.classList.toggle("open");\n'
+ '  document.getElementById("history-tog").textContent=open?"\u25b2":"\u25bc";\n'
+ '}\n'
+ '\n'
// Main state
+ 'var curSurah=null,curAyahIdx=0;\n'
+ 'function getCurrentAyah(){return curSurah?SURAH_MAP[curSurah].ayahs[curAyahIdx]:null;}\n'
+ '\n'
+ 'function savePosition(){try{localStorage.setItem("hifz_pos",JSON.stringify({sn:curSurah,idx:curAyahIdx}));}catch(e){}}\n'
+ '\n'
+ 'function restorePosition(){\n'
+ '  try{\n'
+ '    var p=JSON.parse(localStorage.getItem("hifz_pos"));\n'
+ '    if(!p||!p.sn||!SURAH_MAP[p.sn])return;\n'
+ '    curSurah=p.sn;curAyahIdx=p.idx||0;\n'
+ '    var total=SURAH_MAP[curSurah].ayahs.length;\n'
+ '    curAyahIdx=Math.min(curAyahIdx,total-1);\n'
+ '    sel.value=curSurah;\n'
+ '    document.getElementById("ayah-num").max=total;\n'
+ '    document.getElementById("ayah-num").value=curAyahIdx+1;\n'
+ '    document.getElementById("ayah-of").textContent="/ "+total;\n'
+ '    document.getElementById("hint-btn").style.display="inline-block";\n'
+ '  }catch(e){}\n'
+ '}\n'
+ '\n'
+ 'function onSurahChange(){\n'
+ '  var sn=+sel.value;if(!sn){curSurah=null;return;}\n'
+ '  curSurah=sn;curAyahIdx=0;\n'
+ '  var total=SURAH_MAP[sn].ayahs.length;\n'
+ '  document.getElementById("ayah-num").max=total;\n'
+ '  document.getElementById("ayah-num").value=1;\n'
+ '  document.getElementById("ayah-of").textContent="/ "+total;\n'
+ '  document.getElementById("hint-btn").style.display="inline-block";\n'
+ '  savePosition();clearAll();document.getElementById("inp").focus();\n'
+ '}\n'
+ '\n'
+ 'function onAyahChange(){\n'
+ '  if(!curSurah)return;\n'
+ '  var total=SURAH_MAP[curSurah].ayahs.length;\n'
+ '  var v=Math.max(1,Math.min(parseInt(document.getElementById("ayah-num").value)||1,total));\n'
+ '  document.getElementById("ayah-num").value=v;\n'
+ '  curAyahIdx=v-1;savePosition();clearAll();document.getElementById("inp").focus();\n'
+ '}\n'
+ '\n'
+ 'function prevAyah(){if(curSurah&&curAyahIdx>0){curAyahIdx--;document.getElementById("ayah-num").value=curAyahIdx+1;savePosition();clearAll();document.getElementById("inp").focus();}}\n'
+ 'function nextAyah(){\n'
+ '  if(!curSurah)return;\n'
+ '  var total=SURAH_MAP[curSurah].ayahs.length;\n'
+ '  if(curAyahIdx<total-1){curAyahIdx++;document.getElementById("ayah-num").value=curAyahIdx+1;savePosition();clearAll();document.getElementById("inp").focus();}\n'
+ '}\n'
+ '\n'
+ 'function doCompare(){\n'
+ '  var raw=document.getElementById("inp").value.trim();\n'
+ '  if(!raw)return;\n'
+ '  var ayah=getCurrentAyah();\n'
+ '  if(!ayah){document.getElementById("score-lbl").textContent="Please select a surah first";return;}\n'
+ '  var rw=ayah.text.split(" ");\n'
+ '  var iw=normInput(raw).split(" ");\n'
+ '  var diff=rw.map(function(r,i){var inp=iw[i]||"";return{r:r,inp:inp,match:isMatch(inp,r),missing:!inp};});\n'
+ '  var mc=diff.filter(function(d){return d.match;}).length;\n'
+ '  var total=diff.length;\n'
+ '  var pct=Math.round(mc/total*100);\n'
+ '  document.getElementById("sf").style.width=pct+"%";\n'
+ '  document.getElementById("sf").style.background=pct>=95?"#5ec48a":pct>=50?"#c8943a":"#e07070";\n'
+ '  document.getElementById("score-lbl").textContent=pct+"% \u00b7 "+mc+"/"+total+" words correct";\n'
+ '  var s=SURAH_MAP[curSurah];\n'
+ '  var label=s.sa+" "+curSurah+":"+ayah.an;\n'
+ '  document.getElementById("ref-meta").textContent=s.sa+" \u00b7 "+s.se+" "+curSurah+":"+ayah.an;\n'
+ '  document.getElementById("ref-out").innerHTML=diff.map(function(d){var cls=d.missing?"w-missing":d.match?"w-match":"w-wrong";return"<span class=\'"+cls+"\'>" +d.r+" </span>";}).join("");\n'
// Push to history
+ '  pushHistory({label:label,typed:raw,diff:diff,pct:pct});\n'
+ '  if(pct>=95){\n'
+ '    var panel=document.getElementById("ref-panel");\n'
+ '    panel.classList.add("success-flash");\n'
+ '    setTimeout(function(){panel.classList.remove("success-flash");nextAyah();},800);\n'
+ '  }\n'
+ '}\n'
+ '\n'
+ 'function showHint(){\n'
+ '  var ayah=getCurrentAyah();if(!ayah)return;\n'
+ '  var words=ayah.text.split(" ");\n'
+ '  document.getElementById("ref-out").innerHTML="<span style=\'color:#555;font-style:italic\'>"+words.slice(0,Math.ceil(words.length*0.3)).join(" ")+" \u2026</span>";\n'
+ '  document.getElementById("ref-meta").textContent="hint";\n'
+ '}\n'
+ '\n'
+ 'function clearInput(){\n'
+ '  document.getElementById("inp").value="";\n'
+ '  document.getElementById("ref-out").innerHTML="<span style=\'color:#2a2a2a\'>\u2014</span>";\n'
+ '  document.getElementById("sf").style.width="0%";\n'
+ '  document.getElementById("score-lbl").textContent="";\n'
+ '  document.getElementById("ref-meta").textContent="";\n'
+ '  document.getElementById("inp").focus();\n'
+ '}\n'
+ 'function clearAll(){clearInput();}\n'
+ '\n'
// Keyboard
+ 'function toggleKbd(){\n'
+ '  var k=document.getElementById("kbd-panel");\n'
+ '  var open=k.classList.toggle("open");\n'
+ '  document.getElementById("kbd-toggle-btn").textContent=open?"\u2328\ufe0f":"\u2328";\n'
+ '}\n'
+ 'function kbdInsert(ch){\n'
+ '  var ta=document.getElementById("inp");\n'
+ '  var s=ta.selectionStart,e=ta.selectionEnd,v=ta.value;\n'
+ '  ta.value=v.slice(0,s)+ch+v.slice(e);\n'
+ '  ta.selectionStart=ta.selectionEnd=s+ch.length;\n'
+ '  ta.focus();\n'
+ '}\n'
+ 'function kbdBack(){\n'
+ '  var ta=document.getElementById("inp");\n'
+ '  var s=ta.selectionStart,e=ta.selectionEnd;\n'
+ '  if(s===e&&s>0){ta.value=ta.value.slice(0,s-1)+ta.value.slice(s);ta.selectionStart=ta.selectionEnd=s-1;}\n'
+ '  else if(s!==e){ta.value=ta.value.slice(0,s)+ta.value.slice(e);ta.selectionStart=ta.selectionEnd=s;}\n'
+ '  ta.focus();\n'
+ '}\n'
+ '\n'
+ 'document.getElementById("eq-a").addEventListener("keydown",function(e){if(e.key==="Enter")document.getElementById("eq-b").focus();});\n'
+ 'document.getElementById("eq-b").addEventListener("keydown",function(e){if(e.key==="Enter")addEquiv();});\n'
+ 'document.getElementById("inp").addEventListener("keydown",function(e){\n'
+ '  if(acKeydown(e))return;\n'
+ '  if(e.key==="Enter"&&(e.ctrlKey||e.metaKey))doCompare();\n'
+ '  if((e.key==="i"||e.key==="I"||e.key==="\u06CC")&&(e.ctrlKey||e.metaKey)){e.preventDefault();showHint();}\n'
+ '});\n'
+ 'document.getElementById("inp").addEventListener("input",function(){acSuggest();});\n'
+ 'document.addEventListener("click",function(e){if(!e.target.closest(".ac-wrap")){var d=document.getElementById("ac-drop");if(d){d.classList.remove("open");d.innerHTML="";};}});\n'
+ '\n'
// Autocomplete functions
+ 'var acIdx=-1;\n'
+ 'function getLastPartialWord(val,pos){\n'
+ '  var before=val.slice(0,pos);\n'
+ '  var parts=before.split(" ");\n'
+ '  return parts[parts.length-1]||"";\n'
+ '}\n'
+ 'function acSuggest(){\n'
+ '  var ta=document.getElementById("inp");\n'
+ '  var drop=document.getElementById("ac-drop");\n'
+ '  var word=getLastPartialWord(ta.value,ta.selectionStart);\n'
+ '  if(word.length<2){drop.classList.remove("open");drop.innerHTML="";return;}\n'
+ '  var sugg=(AC[word]||[]).filter(function(s){return s!==word;}).slice(0,5);\n'
+ '  if(!sugg.length){drop.classList.remove("open");drop.innerHTML="";return;}\n'
+ '  acIdx=-1;\n'
+ '  drop.innerHTML=sugg.map(function(s){\n'
+ '    return "<div class=\'ac-item\' data-word=\'"+s+"\' onmousedown=\'acAccept(event,\\\""+s+"\\\")\'>"+s+"</div>";\n'
+ '  }).join("");\n'
+ '  drop.classList.add("open");\n'
+ '}\n'
+ 'function acAccept(e,word){\n'
+ '  if(e)e.preventDefault();\n'
+ '  var ta=document.getElementById("inp");\n'
+ '  var pos=ta.selectionStart;\n'
+ '  var before=ta.value.slice(0,pos);\n'
+ '  var after=ta.value.slice(pos);\n'
+ '  var lastSpace=before.lastIndexOf(" ");\n'
+ '  var newBefore=before.slice(0,lastSpace+1)+word+" ";\n'
+ '  ta.value=newBefore+after;\n'
+ '  ta.selectionStart=ta.selectionEnd=newBefore.length;\n'
+ '  ta.focus();\n'
+ '  var drop=document.getElementById("ac-drop");\n'
+ '  drop.classList.remove("open");drop.innerHTML="";acIdx=-1;\n'
+ '}\n'
+ 'function acKeydown(e){\n'
+ '  var drop=document.getElementById("ac-drop");\n'
+ '  var items=drop.querySelectorAll(".ac-item");\n'
+ '  if(!drop.classList.contains("open")||!items.length)return false;\n'
+ '  if(e.key==="ArrowDown"){e.preventDefault();acIdx=Math.min(acIdx+1,items.length-1);items.forEach(function(el,i){el.classList.toggle("active",i===acIdx);});return true;}\n'
+ '  if(e.key==="ArrowUp"){e.preventDefault();acIdx=Math.max(acIdx-1,-1);items.forEach(function(el,i){el.classList.toggle("active",i===acIdx);});return true;}\n'
+ '  if(e.key==="Tab"||e.key==="\u0027"||e.key==="ArrowLeft"){e.preventDefault();var w=acIdx>=0?items[acIdx].dataset.word:items[0].dataset.word;acAccept(null,w);return true;}\n'
+ '  if(e.key==="Escape"){drop.classList.remove("open");drop.innerHTML="";acIdx=-1;return true;}\n'
+ '  return false;\n'
+ '}\n'
+ '\n'
+ 'loadEquivs();\n'
+ 'restorePosition();\n'
+ 'renderHistory();\n';

function key(ch) {
  return '      <button class="kbd-key" onclick="kbdInsert(\'' + ch + '\')">' + ch + '</button>\n';
}

const html = '<!DOCTYPE html>\n'
+ '<html lang="ar" dir="rtl">\n'
+ '<head>\n'
+ '<meta charset="UTF-8">\n'
+ '<meta name="viewport" content="width=device-width, initial-scale=1.0">\n'
+ '<title>Quran Hifz Practice</title>\n'
+ '<link href="https://fonts.googleapis.com/css2?family=Amiri:wght@400;700&display=swap" rel="stylesheet">\n'
+ '<style>\n' + css + '</style>\n'
+ '</head>\n'
+ '<body>\n'
+ '<div class="container">\n'

// Selector bar
+ '  <div class="selector-bar">\n'
+ '    <select id="surah-sel" onchange="onSurahChange()"><option value="">— Select Surah —</option></select>\n'
+ '    <button class="nav-btn" onclick="prevAyah()">&#8249;</button>\n'
+ '    <input type="number" id="ayah-num" min="1" value="1" onchange="onAyahChange()" onkeydown="if(event.key===\'Enter\')document.getElementById(\'inp\').focus()">\n'
+ '    <span class="ayah-label" id="ayah-of">/ —</span>\n'
+ '    <button class="nav-btn" onclick="nextAyah()">&#8250;</button>\n'
+ '  </div>\n'

// Input panel
+ '  <div class="panel panel-input">\n'
+ '    <span class="panel-label">\u0627\u0643\u062a\u0628 \u0645\u0646 \u062d\u0641\u0638\u0643</span>\n'
+ '    <button class="kbd-toggle" id="kbd-toggle-btn" onclick="toggleKbd()" title="On-screen keyboard" style="position:absolute;top:7px;left:12px">\u2328</button>\n'
+ '    <div class="ac-wrap">\n'
+ '      <textarea id="inp" dir="rtl" autocomplete="off" autocorrect="off" autocapitalize="off" spellcheck="false"></textarea>\n'
+ '      <div id="ac-drop" class="ac-drop"></div>\n'
+ '    </div>\n'
+ '    <div class="score-bar"><div class="score-fill" id="sf"></div></div>\n'
+ '  </div>\n'

// On-screen keyboard
+ '  <div class="kbd-panel" id="kbd-panel">\n'
+ '    <div class="kbd-row">\n'
+ key('\u0636') + key('\u0635') + key('\u062b') + key('\u0642') + key('\u0641') + key('\u063a') + key('\u0639') + key('\u0647') + key('\u062e') + key('\u062d') + key('\u062c') + key('\u062f')
+ '    </div>\n'
+ '    <div class="kbd-row">\n'
+ key('\u0634') + key('\u0633') + key('\u064a') + key('\u0628') + key('\u0644') + key('\u0627') + key('\u062a') + key('\u0646') + key('\u0645') + key('\u0643') + key('\u0637')
+ '    </div>\n'
+ '    <div class="kbd-row">\n'
+ key('\u0626') + key('\u0621') + key('\u0624') + key('\u0631') + key('\u0649') + key('\u0629') + key('\u0648') + key('\u0632') + key('\u0638') + key('\u0630') + key('\u0644\u0627')
+ '    </div>\n'
+ '    <div class="kbd-row">\n'
+ key('\u0623') + key('\u0625') + key('\u0622')
+ '      <button class="kbd-key space" onclick="kbdInsert(\' \')">space</button>\n'
+ '      <button class="kbd-key wide" onclick="kbdBack()">&#9003;</button>\n'
+ '    </div>\n'
+ '  </div>\n'

// Toolbar
+ '  <div class="toolbar">\n'
+ '    <button class="action primary" onclick="doCompare()">Compare</button>\n'
+ '    <button class="action" onclick="clearInput()">Clear</button>\n'
+ '    <button class="action" id="hint-btn" onclick="showHint()" style="display:none">Hint</button>\n'
+ '    <span id="score-lbl" class="meta"></span>\n'
+ '  </div>\n'

// Reference panel
+ '  <div class="panel panel-ref" id="ref-panel">\n'
+ '    <span class="panel-label">\u0627\u0644\u0646\u0635 \u0627\u0644\u0635\u062d\u064a\u062d</span>\n'
+ '    <div class="ref-text" id="ref-out"><span style="color:#2a2a2a">\u2014</span></div>\n'
+ '    <span class="ref-meta" id="ref-meta"></span>\n'
+ '  </div>\n'

// History panel
+ '  <div class="history-panel">\n'
+ '    <div class="history-header" onclick="toggleHistory()">\n'
+ '      <span>Previous ayaat <span id="history-count"></span></span>\n'
+ '      <span id="history-tog" style="font-size:10px;color:#444">\u25bc</span>\n'
+ '    </div>\n'
+ '    <div class="history-scroll" id="history-scroll">\n'
+ '      <div id="history-list"></div>\n'
+ '    </div>\n'
+ '  </div>\n'

// Equivalents panel
+ '  <div class="equiv-panel">\n'
+ '    <div class="equiv-header" onclick="toggleEquiv()">\n'
+ '      <span>Equivalent pairs <span id="equiv-count"></span></span>\n'
+ '      <span id="equiv-tog" style="font-size:10px;color:#444">\u25bc</span>\n'
+ '    </div>\n'
+ '    <div class="equiv-body" id="equiv-body">\n'
+ '      <div class="equiv-add">\n'
+ '        <input id="eq-a" dir="rtl" placeholder="\u0643\u062a\u0628" autocomplete="off" autocorrect="off" spellcheck="false">\n'
+ '        <span class="sep">=</span>\n'
+ '        <input id="eq-b" dir="rtl" placeholder="\u0643\u062a\u0627\u0628" autocomplete="off" autocorrect="off" spellcheck="false">\n'
+ '        <button class="action" onclick="addEquiv()">Add</button>\n'
+ '      </div>\n'
+ '      <div id="equiv-list" class="equiv-list"></div>\n'
+ '    </div>\n'
+ '  </div>\n'

+ '</div>\n'
+ '<script>\n' + js + '</script>\n'
+ '</body>\n'
+ '</html>\n';

fs.writeFileSync('/home/claude/quran_hifz_v5.html', html);
const size = fs.statSync('/home/claude/quran_hifz_v5.html').size;
console.log('HTML written:', (size/1024).toFixed(1), 'KB');
